### ISSUE TITLE
Boardwalk indexer for Commons minimal metadata

### ISSUE THREAD

**Issue by caaespin** [BD2KGenomics/dss-azul-indexer#19]
We need to customize the indexer to work with the Commons metadata.  That is, dss-azul should be able to index the commons metadata via eventing from the blue box.

**Comment by caaespin** [comment]
UPDATE: Not done yet. Waiting for the 12k and the new metadata to be ingested to test

**Comment by mikebaumann** [comment]
Reopening after accidentally closing.
